name: Build and upload release artifacts

on:
  release:
    types:
      - created

jobs:
  linux:
    runs-on: 'ubuntu-latest'
    steps:
      - uses: actions/checkout@v1
      - name: Build release artifacts
        run: ./scripts/buildrelease.sh
      - name: upload Linux release artifacts
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./jmc/target/products/org.openjdk.jmc-linux.gtk.x86_64.tar.gz
          asset_name: org.openjdk.jmc-linux.gtk.x86_64.tar.gz
          asset_content_type: application/gzip
      - name: upload OSX release artifacts
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./jmc/target/products/org.openjdk.jmc-macosx.cocoa.x86_64.tar.gz
          asset_name: org.openjdk.jmc-macosx.cocoa.x86_64.tar.gz
          asset_content_type: application/gzip
      - name: upload Windows release artifacts
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./jmc/target/products/org.openjdk.jmc-win32.win32.x86_64.zip
          asset_name: org.openjdk.jmc-win32.win32.x86_64.zip
          asset_content_type: application/zip
