name: Check formatting and run tests

on: [push, pull_request]

jobs:
  linux:
    runs-on: 'ubuntu-latest'
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Build JMC
        run: ./scripts/buildjmc.sh
      - name: Check formatting
        run: ./scripts/checkformatting.sh
      - name: Run tests
        run: ./scripts/runtests.sh